package com.James.corporateportraitplatforms.mapper;

import com.James.corporateportraitplatforms.model.KnowledgeReport;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface KnowledgeReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Delete({
        "delete from knowledge_report",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Insert({
        "insert into knowledge_report (cid, patent, ",
        "trademark, copyright)",
        "values (#{cid,jdbcType=VARCHAR}, #{patent,jdbcType=VARCHAR}, ",
        "#{trademark,jdbcType=VARCHAR}, #{copyright,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys = true)
    Long insert(KnowledgeReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Select({
        "select",
        "id, cid, patent, trademark, copyright",
        "from knowledge_report",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
        @Result(column="patent", property="patent", jdbcType=JdbcType.VARCHAR),
        @Result(column="trademark", property="trademark", jdbcType=JdbcType.VARCHAR),
        @Result(column="copyright", property="copyright", jdbcType=JdbcType.VARCHAR)
    })
    KnowledgeReport selectByPrimaryKey(Long id);

    @Select({
            "select",
            "id, cid, patent, trademark, copyright",
            "from knowledge_report",
            "where cid = #{cid,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
            @Result(column="patent", property="patent", jdbcType=JdbcType.VARCHAR),
            @Result(column="trademark", property="trademark", jdbcType=JdbcType.VARCHAR),
            @Result(column="copyright", property="copyright", jdbcType=JdbcType.VARCHAR)
    })
    KnowledgeReport selectByCid(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Select({
        "select",
        "id, cid, patent, trademark, copyright",
        "from knowledge_report"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
        @Result(column="patent", property="patent", jdbcType=JdbcType.VARCHAR),
        @Result(column="trademark", property="trademark", jdbcType=JdbcType.VARCHAR),
        @Result(column="copyright", property="copyright", jdbcType=JdbcType.VARCHAR)
    })
    List<KnowledgeReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Update({
        "update knowledge_report",
        "set cid = #{cid,jdbcType=VARCHAR},",
          "patent = #{patent,jdbcType=VARCHAR},",
          "trademark = #{trademark,jdbcType=VARCHAR},",
          "copyright = #{copyright,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(KnowledgeReport record);
}