package com.James.corporateportraitplatforms.mapper;

import com.James.corporateportraitplatforms.model.MoneyReport;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;


@Mapper
@Repository
public interface MoneyReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Delete({
        "delete from money_report",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    @Delete("delete from money_report")
    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Insert({
        "insert into money_report (cid, year, ",
        "debt_financing_line, debt_financing_cost, ",
        "equity_financing_line, equity_financing_cost, ",
        "internal_financing_and_trade_financing_line, ",
        "internal_financing_and_trade_financing_costs, ",
        "project_financing_and_policy_financing_quotas, ",
        "project_financing_and_policy_financing_costs)",
        "values (#{cid,jdbcType=VARCHAR}, #{year,jdbcType=VARCHAR}, ",
        "#{debtFinancingLine,jdbcType=VARCHAR}, #{debtFinancingCost,jdbcType=VARCHAR}, ",
        "#{equityFinancingLine,jdbcType=VARCHAR}, #{equityFinancingCost,jdbcType=VARCHAR}, ",
        "#{internalFinancingAndTradeFinancingLine,jdbcType=VARCHAR}, ",
        "#{internalFinancingAndTradeFinancingCosts,jdbcType=VARCHAR}, ",
        "#{projectFinancingAndPolicyFinancingQuotas,jdbcType=VARCHAR}, ",
        "#{projectFinancingAndPolicyFinancingCosts,jdbcType=VARCHAR})"
    })
    //@SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    @Options(useGeneratedKeys = true)
    int insert(MoneyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Select({
        "select",
        "id, cid, year, debt_financing_line, debt_financing_cost, equity_financing_line, ",
        "equity_financing_cost, internal_financing_and_trade_financing_line, internal_financing_and_trade_financing_costs, ",
        "project_financing_and_policy_financing_quotas, project_financing_and_policy_financing_costs",
        "from money_report",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
        @Result(column="year", property="year", jdbcType=JdbcType.VARCHAR),
        @Result(column="debt_financing_line", property="debtFinancingLine", jdbcType=JdbcType.VARCHAR),
        @Result(column="debt_financing_cost", property="debtFinancingCost", jdbcType=JdbcType.VARCHAR),
        @Result(column="equity_financing_line", property="equityFinancingLine", jdbcType=JdbcType.VARCHAR),
        @Result(column="equity_financing_cost", property="equityFinancingCost", jdbcType=JdbcType.VARCHAR),
        @Result(column="internal_financing_and_trade_financing_line", property="internalFinancingAndTradeFinancingLine", jdbcType=JdbcType.VARCHAR),
        @Result(column="internal_financing_and_trade_financing_costs", property="internalFinancingAndTradeFinancingCosts", jdbcType=JdbcType.VARCHAR),
        @Result(column="project_financing_and_policy_financing_quotas", property="projectFinancingAndPolicyFinancingQuotas", jdbcType=JdbcType.VARCHAR),
        @Result(column="project_financing_and_policy_financing_costs", property="projectFinancingAndPolicyFinancingCosts", jdbcType=JdbcType.VARCHAR)
    })
    MoneyReport selectByPrimaryKey(Long id);

    @Select({
            "select",
            "id, cid, year, debt_financing_line, debt_financing_cost, equity_financing_line, ",
            "equity_financing_cost, internal_financing_and_trade_financing_line, internal_financing_and_trade_financing_costs, ",
            "project_financing_and_policy_financing_quotas, project_financing_and_policy_financing_costs",
            "from money_report",
            "where cid = #{cid,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
            @Result(column="year", property="year", jdbcType=JdbcType.VARCHAR),
            @Result(column="debt_financing_line", property="debtFinancingLine", jdbcType=JdbcType.VARCHAR),
            @Result(column="debt_financing_cost", property="debtFinancingCost", jdbcType=JdbcType.VARCHAR),
            @Result(column="equity_financing_line", property="equityFinancingLine", jdbcType=JdbcType.VARCHAR),
            @Result(column="equity_financing_cost", property="equityFinancingCost", jdbcType=JdbcType.VARCHAR),
            @Result(column="internal_financing_and_trade_financing_line", property="internalFinancingAndTradeFinancingLine", jdbcType=JdbcType.VARCHAR),
            @Result(column="internal_financing_and_trade_financing_costs", property="internalFinancingAndTradeFinancingCosts", jdbcType=JdbcType.VARCHAR),
            @Result(column="project_financing_and_policy_financing_quotas", property="projectFinancingAndPolicyFinancingQuotas", jdbcType=JdbcType.VARCHAR),
            @Result(column="project_financing_and_policy_financing_costs", property="projectFinancingAndPolicyFinancingCosts", jdbcType=JdbcType.VARCHAR)
    })
    MoneyReport selectByCid(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Select({
        "select",
        "id, cid, year, debt_financing_line, debt_financing_cost, equity_financing_line, ",
        "equity_financing_cost, internal_financing_and_trade_financing_line, internal_financing_and_trade_financing_costs, ",
        "project_financing_and_policy_financing_quotas, project_financing_and_policy_financing_costs",
        "from money_report"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
        @Result(column="year", property="year", jdbcType=JdbcType.VARCHAR),
        @Result(column="debt_financing_line", property="debtFinancingLine", jdbcType=JdbcType.VARCHAR),
        @Result(column="debt_financing_cost", property="debtFinancingCost", jdbcType=JdbcType.VARCHAR),
        @Result(column="equity_financing_line", property="equityFinancingLine", jdbcType=JdbcType.VARCHAR),
        @Result(column="equity_financing_cost", property="equityFinancingCost", jdbcType=JdbcType.VARCHAR),
        @Result(column="internal_financing_and_trade_financing_line", property="internalFinancingAndTradeFinancingLine", jdbcType=JdbcType.VARCHAR),
        @Result(column="internal_financing_and_trade_financing_costs", property="internalFinancingAndTradeFinancingCosts", jdbcType=JdbcType.VARCHAR),
        @Result(column="project_financing_and_policy_financing_quotas", property="projectFinancingAndPolicyFinancingQuotas", jdbcType=JdbcType.VARCHAR),
        @Result(column="project_financing_and_policy_financing_costs", property="projectFinancingAndPolicyFinancingCosts", jdbcType=JdbcType.VARCHAR)
    })
    List<MoneyReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Update({
        "update money_report",
        "set cid = #{cid,jdbcType=VARCHAR},",
          "year = #{year,jdbcType=VARCHAR},",
          "debt_financing_line = #{debtFinancingLine,jdbcType=VARCHAR},",
          "debt_financing_cost = #{debtFinancingCost,jdbcType=VARCHAR},",
          "equity_financing_line = #{equityFinancingLine,jdbcType=VARCHAR},",
          "equity_financing_cost = #{equityFinancingCost,jdbcType=VARCHAR},",
          "internal_financing_and_trade_financing_line = #{internalFinancingAndTradeFinancingLine,jdbcType=VARCHAR},",
          "internal_financing_and_trade_financing_costs = #{internalFinancingAndTradeFinancingCosts,jdbcType=VARCHAR},",
          "project_financing_and_policy_financing_quotas = #{projectFinancingAndPolicyFinancingQuotas,jdbcType=VARCHAR},",
          "project_financing_and_policy_financing_costs = #{projectFinancingAndPolicyFinancingCosts,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MoneyReport record);


    void insertBatch(@Param("list") List<MoneyReport> MoneyReportList);
}
