package com.James.corporateportraitplatforms.mapper;

import com.James.corporateportraitplatforms.model.YearReport;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;
import sweeneyhe.bean.YearBean;


@Mapper
@Repository
public interface YearReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Delete({
        "delete from year_report",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    @Delete("delete from year_report")
    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Insert({
        "insert into year_report (cid, year, ",
        "number_of_employees, total_assets, ",
        "total_liabilities, total_operating_income, ",
        "main_business_income, total_profit, ",
        "net_profit, total_tax, ",
        "total_owner_equity)",
        "values (#{cid,jdbcType=VARCHAR}, #{year,jdbcType=VARCHAR}, ",
        "#{numberOfEmployees,jdbcType=VARCHAR}, #{totalAssets,jdbcType=VARCHAR}, ",
        "#{totalLiabilities,jdbcType=VARCHAR}, #{totalOperatingIncome,jdbcType=VARCHAR}, ",
        "#{mainBusinessIncome,jdbcType=VARCHAR}, #{totalProfit,jdbcType=VARCHAR}, ",
        "#{netProfit,jdbcType=VARCHAR}, #{totalTax,jdbcType=VARCHAR}, ",
        "#{totalOwnerEquity,jdbcType=VARCHAR})"
    })
    //@SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    @Options(useGeneratedKeys = true)
    int insert(YearReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Select({
        "select",
        "id, cid, year, number_of_employees, total_assets, total_liabilities, total_operating_income, ",
        "main_business_income, total_profit, net_profit, total_tax, total_owner_equity",
        "from year_report",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
        @Result(column="year", property="year", jdbcType=JdbcType.VARCHAR),
        @Result(column="number_of_employees", property="numberOfEmployees", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_assets", property="totalAssets", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_liabilities", property="totalLiabilities", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_operating_income", property="totalOperatingIncome", jdbcType=JdbcType.VARCHAR),
        @Result(column="main_business_income", property="mainBusinessIncome", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_profit", property="totalProfit", jdbcType=JdbcType.VARCHAR),
        @Result(column="net_profit", property="netProfit", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_tax", property="totalTax", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_owner_equity", property="totalOwnerEquity", jdbcType=JdbcType.VARCHAR)
    })
    YearReport selectByPrimaryKey(Long id);

    @Select({
            "select",
            "id, cid, year, number_of_employees, total_assets, total_liabilities, total_operating_income, ",
            "main_business_income, total_profit, net_profit, total_tax, total_owner_equity",
            "from year_report",
            "where cid = #{cid,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
            @Result(column="year", property="year", jdbcType=JdbcType.VARCHAR),
            @Result(column="number_of_employees", property="numberOfEmployees", jdbcType=JdbcType.VARCHAR),
            @Result(column="total_assets", property="totalAssets", jdbcType=JdbcType.VARCHAR),
            @Result(column="total_liabilities", property="totalLiabilities", jdbcType=JdbcType.VARCHAR),
            @Result(column="total_operating_income", property="totalOperatingIncome", jdbcType=JdbcType.VARCHAR),
            @Result(column="main_business_income", property="mainBusinessIncome", jdbcType=JdbcType.VARCHAR),
            @Result(column="total_profit", property="totalProfit", jdbcType=JdbcType.VARCHAR),
            @Result(column="net_profit", property="netProfit", jdbcType=JdbcType.VARCHAR),
            @Result(column="total_tax", property="totalTax", jdbcType=JdbcType.VARCHAR),
            @Result(column="total_owner_equity", property="totalOwnerEquity", jdbcType=JdbcType.VARCHAR)
    })
    YearReport selectByCid(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Select({
        "select",
        "id, cid, year, number_of_employees, total_assets, total_liabilities, total_operating_income, ",
        "main_business_income, total_profit, net_profit, total_tax, total_owner_equity",
        "from year_report"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="cid", property="cid", jdbcType=JdbcType.VARCHAR),
        @Result(column="year", property="year", jdbcType=JdbcType.VARCHAR),
        @Result(column="number_of_employees", property="numberOfEmployees", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_assets", property="totalAssets", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_liabilities", property="totalLiabilities", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_operating_income", property="totalOperatingIncome", jdbcType=JdbcType.VARCHAR),
        @Result(column="main_business_income", property="mainBusinessIncome", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_profit", property="totalProfit", jdbcType=JdbcType.VARCHAR),
        @Result(column="net_profit", property="netProfit", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_tax", property="totalTax", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_owner_equity", property="totalOwnerEquity", jdbcType=JdbcType.VARCHAR)
    })
    List<YearReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year_report
     *
     * @mbg.generated Wed Feb 12 12:51:31 CST 2020
     */
    @Update({
        "update year_report",
        "set cid = #{cid,jdbcType=VARCHAR},",
          "year = #{year,jdbcType=VARCHAR},",
          "number_of_employees = #{numberOfEmployees,jdbcType=VARCHAR},",
          "total_assets = #{totalAssets,jdbcType=VARCHAR},",
          "total_liabilities = #{totalLiabilities,jdbcType=VARCHAR},",
          "total_operating_income = #{totalOperatingIncome,jdbcType=VARCHAR},",
          "main_business_income = #{mainBusinessIncome,jdbcType=VARCHAR},",
          "total_profit = #{totalProfit,jdbcType=VARCHAR},",
          "net_profit = #{netProfit,jdbcType=VARCHAR},",
          "total_tax = #{totalTax,jdbcType=VARCHAR},",
          "total_owner_equity = #{totalOwnerEquity,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(YearReport record);

    void insertBatch(@Param("list") List<YearReport> YearReportList);

    void insertBatch_(@Param("list") List<YearBean> YearReportList);
}
