server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://59.110.143.147:3306/bisai?serverTimezone=Asia/Shanghai
    username: bisai
    password: qihang123456789

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: 'classpath*:mapper/**/*.xml'
  type-aliases-package: com.James.corporateportraitplatforms.model


pagehelper:
  offset-as-page-num: true
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true


logging:
  level:
    com:
      James:
        corporateportraitplatforms:
          mapper: debug


